language: cpp
sudo: false


matrix:
  include:
    # Linux Clang
    - os: linux
      compiler: clang

    # Linux GCC
    - os: linux
      compiler: gcc


install:
  # Getting Boost for testing
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      sudo apt-get install libboost-test-dev; 
    fi

  # Getting CMake for building
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  - cmake --version

  # Getting Doxygen for documentation
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install doxygen; 
    fi
  
  # Getting latest version of LCOV for the linux debug build
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$CONFIG" == "DEBUG" ]]; then
       wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
       tar xf lcov_1.11.orig.tar.gz
       sudo make -C lcov-1.11/ install
       sudo apt-get install ruby1.9.1 ruby1.9.1-dev
       sudo apt-get install rubygems1.9.1 irb1.9.1 ri1.9.1
       rvmsudo gem install coveralls-lcov
    fi


before_script:
  # Set up the git identity (for pushing documentation)
  - git config --global user.name "Travis bot"
  - git config --global user.email "<>"

  # Initialize coverage to 0 on the Linux debug build
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$CONFIG" == "DEBUG" ]]; then 
       cd ${TRAVIS_BUILD_DIR}
       lcov --directory . --zerocounters
    fi


script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  - ctest
  #- python testrunner.py ${TRAVIS_BUILD_DIR} ${TRAVIS_BUILD_DIR}


after_success:
  # Sending coverage info collected with the Linux debug build
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$CONFIG" == "DEBUG" ]]; then 
       cd ${TRAVIS_BUILD_DIR}
       lcov --directory . --capture --output-file coverage.info
       lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
       lcov --list coverage.info
       coveralls-lcov coverage.info
    fi
  
